import {
  urlSet,
  validateArticles,
  type PageUrl,
  type SchemeViolation,
} from '@robusta/pyramids-routing';
import { getArticleIndex } from '../content/article-index.js';
import { urlScheme } from './scheme.js';

/**
 * The route table comes in two halves that mirror each other: the seven files
 * under the default locale, whose params carry no locale because the default
 * one is unmarked, and the seven under `l/[locale]`, whose params carry it.
 */
export type LocaleScope = 'default-locale' | 'other-locales';

type RouteParams = Record<string, string>;

/**
 * The one derivation of the URL set that feeds every route's pregeneration
 * (R-URLSCHEME-22). The v1 failure mode — a URL pregenerated by one list and
 * refused at request time by a second — has no place to occur, because there is
 * no second list.
 *
 * It is also where a corpus that breaks the scheme stops the build:
 * `validateArticles` returns violations and never throws, and this caller is the
 * one that decides a non-empty result is fatal (R-URLSCHEME-11 and 12).
 */
export async function contentUrls(): Promise<PageUrl[]> {
  const articles = await getArticleIndex();

  const violations = validateArticles(urlScheme, articles);
  if (violations.length > 0) {
    const lines = violations.map((violation) => `  - ${describe(violation)}`);
    throw new Error(`The article corpus breaks the URL scheme:\n${lines.join('\n')}`);
  }

  return urlSet(urlScheme, articles);
}

/** `/{contentRoot}/p/{n}`: the roll pages of the blog home, from two. */
export async function rollPageParams(scope: LocaleScope): Promise<RouteParams[]> {
  return (await pagesOfKind('blog-home', scope))
    .filter((page) => page.page > 1)
    .map((page) => ({ ...localeOf(page, scope), n: String(page.page) }));
}

/** `/l/{locale}/{contentRoot}`: the blog home of every non-default locale that has one. */
export async function blogHomeParams(): Promise<RouteParams[]> {
  return (await pagesOfKind('blog-home', 'other-locales'))
    .filter((page) => page.page === 1)
    .map((page) => ({ locale: page.locale }));
}

/**
 * `/l/{locale}`: empty today. The locale-prefixed landing is part of the shape,
 * and its copy is robusta-landing-page's, so the derivation produces no landing
 * page and this route emits nothing.
 */
export async function landingParams(): Promise<RouteParams[]> {
  return (await pagesOfKind('landing', 'other-locales')).map((page) => ({
    locale: page.locale,
  }));
}

/** `/{contentRoot}/c/{category}`: one per category an article of that locale claims. */
export async function categoryParams(scope: LocaleScope): Promise<RouteParams[]> {
  return (await pagesOfKind('category', scope))
    .filter((page) => page.page === 1)
    .map((page) => ({ ...localeOf(page, scope), category: page.category }));
}

/** `/{contentRoot}/c/{category}/p/{n}`: the roll pages of a category, from two. */
export async function categoryRollPageParams(
  scope: LocaleScope,
): Promise<RouteParams[]> {
  return (await pagesOfKind('category', scope))
    .filter((page) => page.page > 1)
    .map((page) => ({
      ...localeOf(page, scope),
      category: page.category,
      n: String(page.page),
    }));
}

/** `/{contentRoot}/{slug}`: the articles carrying no category. */
export async function looseArticleParams(scope: LocaleScope): Promise<RouteParams[]> {
  return (await pagesOfKind('article', scope))
    .filter((page) => page.category === undefined)
    .map((page) => ({ ...localeOf(page, scope), slug: page.slug }));
}

/** `/{contentRoot}/c/{category}/{slug}`: the articles carrying one. */
export async function categorisedArticleParams(
  scope: LocaleScope,
): Promise<RouteParams[]> {
  return (await pagesOfKind('article', scope))
    .filter((page) => page.category !== undefined)
    .map((page) => ({
      ...localeOf(page, scope),
      category: page.category as string,
      slug: page.slug,
    }));
}

type PageOfKind<K extends PageUrl['kind']> = Extract<PageUrl, { kind: K }>;

async function pagesOfKind<K extends PageUrl['kind']>(
  kind: K,
  scope: LocaleScope,
): Promise<PageOfKind<K>[]> {
  const isDefault = (locale: string) => locale === urlScheme.defaultLocale;
  const inScope = (locale: string) =>
    scope === 'default-locale' ? isDefault(locale) : !isDefault(locale);

  return (await contentUrls()).filter(
    (page): page is PageOfKind<K> => page.kind === kind && inScope(page.locale),
  );
}

function localeOf(page: PageUrl, scope: LocaleScope): RouteParams {
  return scope === 'default-locale' ? {} : { locale: page.locale };
}

function describe(violation: SchemeViolation): string {
  switch (violation.code) {
    case 'reserved-segment':
      return `article '${violation.slug}': '${violation.segment}' is a discriminant of the scheme and can be neither a slug nor a category`;
    case 'duplicate-slug':
      return `two articles of locale '${violation.locale}' share the slug '${violation.slug}'`;
    case 'nested-category':
      return `article '${violation.slug}': the category '${violation.category}' nests, and a category is exactly one segment`;
    case 'unknown-locale':
      return `article '${violation.slug}': the locale '${violation.locale}' is not one the site configuration declares`;
    case 'non-canonical-segment':
      return `article '${violation.slug}': the segment '${violation.segment}' is not lowercase ASCII words joined by single hyphens`;
  }
}
